/**
 * Seeds 5 Dashboard documentation articles into the database.
 *
 * Usage: npx tsx scripts/seed-dashboard-docs.ts
 */

import dotenv from "dotenv";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

dotenv.config();

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error("DATABASE_URL is required");
  process.exit(1);
}

const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

/* ------------------------------------------------------------------ */
/*  Article content                                                    */
/* ------------------------------------------------------------------ */

const articles = [
  /* ================================================================ */
  /*  1. Dashboards Overview                                           */
  /* ================================================================ */
  {
    slug: "dashboards-overview",
    title: "Dashboards Overview",
    description:
      "Build custom dashboards with AI-generated widgets — scorecards, charts, and tables from plain English.",
    section: "docs",
    category: "dashboards",
    type: "article",
    readTime: "3 min read",
    featured: true,
    keywords: ["dashboards", "overview", "widgets", "analytics", "ai"],
    content: `---
---

Dashboards give you a persistent, at-a-glance view of the metrics that matter most. Drag, drop, and resize widgets on a flexible grid — each one generated by AI from a plain-English prompt.

<DocsDemo type="full-dashboard" />

## What dashboards are

A dashboard is a collection of widgets arranged on a drag-and-drop grid. You describe what you want to see, the AI generates the widget, and it stays on your dashboard, refreshing automatically every time you open it.

There is no manual chart configuration, no query builder, and no SQL. Just tell the AI what you want in plain English and it handles the rest.

## Widget types

Every widget falls into one of three categories:

- **Scorecards** — A single metric with an optional comparison to the previous period. Ideal for KPIs you check daily, like total sessions or ad spend.
- **Charts** — Bar charts, line charts, pie charts, and sankey diagrams for visualising trends, distributions, and flows.
- **Tables** — Sortable data tables for detailed breakdowns and ranked lists.

See [Widget Types](/docs/dashboards/widget-types) for a deep dive on each format and when to use them.

## Real-time data from BigQuery

All widgets query your BigQuery data warehouse directly. This means you are always looking at the same authoritative data that powers the AI chat — no stale exports or manual imports.

Widgets cache their last-fetched data so dashboards load instantly, then silently refresh in the background when you open them.

## Supported data sources

Dashboards can pull from any platform connected to your organisation:

- Google Analytics 4
- Google Ads
- Microsoft Ads
- LinkedIn
- Mailchimp
- Google Search Console

You can mix data sources on a single dashboard — for example, a GA4 sessions scorecard next to a Google Ads spend chart and a LinkedIn engagement table.

## Next steps

- [Creating Your First Dashboard](/docs/dashboards/creating-first-dashboard) — step-by-step guide
- [Widget Types](/docs/dashboards/widget-types) — scorecards, charts, and tables explained
- [Editing & Organising](/docs/dashboards/editing-organising) — drag, resize, rename, and manage widgets
- [Date Ranges & Refresh](/docs/dashboards/date-ranges-refresh) — control time periods and keep data fresh
`,
  },

  /* ================================================================ */
  /*  2. Creating Your First Dashboard                                 */
  /* ================================================================ */
  {
    slug: "creating-first-dashboard",
    title: "Creating Your First Dashboard",
    description:
      "Create a dashboard, add your first widget, and see AI-generated analytics in seconds.",
    section: "docs",
    category: "dashboards",
    type: "guide",
    readTime: "2 min read",
    featured: false,
    keywords: ["create", "first dashboard", "guide", "add widget", "getting started"],
    content: `---
---

You can go from zero to a working dashboard with real data in under a minute. Here is how.

## Step 1: Open dashboards

Click **Dashboards** in the sidebar. You will see a list of your existing dashboards, or an empty state if this is your first.

## Step 2: Create a new dashboard

Click the **New** button at the top. A fresh, empty dashboard opens with a title you can edit inline.

## Step 3: Add your first widget

Click **+ Add Widget** in the header bar, or click the call-to-action in the empty state. A prompt dialog appears.

## Step 4: Describe what you want

Type a plain-English description of the metric, chart, or table you want. Be specific about the metric, time range, and format. A few examples:

- "Bar chart of daily sessions for the last 30 days"
- "Total Google Ads spend this month as a scorecard"
- "Top 10 pages by pageviews as a table"

The more context you provide, the more accurate the result.

## Step 5: Wait for the AI to generate

The AI translates your prompt into a BigQuery query, fetches the data, and renders the widget. This typically takes 5 to 12 seconds depending on the complexity of the query.

## Step 6: See your widget

Your widget appears on the grid with real data from your connected platforms. You can immediately interact with it — sort tables, hover over charts, or read scorecard comparisons.

<DocsDemo type="full-dashboard" />

## Keep going

Add more widgets to build out your dashboard. Each new widget slots into the grid automatically, and you can drag and resize them to create the layout you want.

There is no limit to the number of widgets on a single dashboard. Organise them however makes sense for your workflow — one dashboard per client, per channel, or per reporting cadence.
`,
  },

  /* ================================================================ */
  /*  3. Widget Types                                                   */
  /* ================================================================ */
  {
    slug: "widget-types",
    title: "Widget Types",
    description:
      "Scorecards, charts, and tables — understand each widget type and when to use them.",
    section: "docs",
    category: "dashboards",
    type: "article",
    readTime: "4 min read",
    featured: false,
    keywords: ["widget", "scorecard", "chart", "table", "bar", "line", "pie", "sankey"],
    content: `---
---

Every dashboard widget is one of three types. The AI chooses the best format based on your prompt, but you can also specify exactly what you want.

<DocsDemo type="widget-types" />

## Scorecards

A scorecard displays a single metric front and centre, with an optional comparison to the previous period.

**What you see:**
- The primary value, large and prominent
- A label describing the metric
- A percentage change with an up or down indicator, coloured green for improvement and red for decline

**Best for:** KPIs and totals you check daily — sessions, spend, follower count, conversion totals.

**Example prompts:**
- "Total sessions this month"
- "Current LinkedIn follower count"
- "Google Ads spend last 7 days"
- "Mailchimp audience size"

## Charts

Charts visualise trends, comparisons, and proportions. The AI supports several chart types and picks the most appropriate one based on your prompt.

**Bar charts** work best for comparing categories side by side. Use them when you want to rank or compare discrete items.
- "Top 10 landing pages by sessions"
- "Campaign performance by clicks"
- "Sessions by device category"

**Line charts** work best for trends over time. Use them when you want to see how a metric changes day by day or week by week.
- "Daily sessions for the last 30 days"
- "Weekly Google Ads spend trend"
- "Monthly new users over the past year"

**Pie charts** work best for showing proportions. Use them when you want to see how a total breaks down into parts.
- "Traffic by device category"
- "Sessions by channel grouping"
- "Ad spend split by campaign"

**Sankey diagrams** work best for visualising flows. Use them when you want to see how users move from one stage or page to another.
- "User flow from landing page to conversion"
- "Page-to-page navigation paths"

## Tables

Tables present structured data in sortable rows and columns with automatic formatting.

**Features:**
- Click any column header to sort ascending or descending
- Numbers are right-aligned with comma formatting for readability
- URLs are auto-cleaned, stripping the https:// prefix
- Large datasets are paginated for performance

**Best for:** Detailed breakdowns, ranked lists, and raw data exploration where you need to scan multiple dimensions at once.

**Example prompts:**
- "Top 20 search queries by clicks"
- "Campaign performance breakdown with impressions, clicks, cost, and conversions"
- "Landing page report: page, sessions, bounce rate, and average duration"
- "All Mailchimp campaigns this quarter with open rate and click rate"
`,
  },

  /* ================================================================ */
  /*  4. Editing & Organising                                          */
  /* ================================================================ */
  {
    slug: "editing-organising",
    title: "Editing & Organising",
    description:
      "Drag, resize, rename, and manage your dashboard widgets.",
    section: "docs",
    category: "dashboards",
    type: "guide",
    readTime: "3 min read",
    featured: false,
    keywords: ["edit", "drag", "resize", "rename", "delete", "organise", "layout"],
    content: `---
---

Once you have added widgets to your dashboard, you can rearrange, resize, and customise them to match your workflow.

<DocsDemo type="drag-resize" />

## Moving widgets

Drag the grip handle in the widget header to reposition it on the grid. Other widgets automatically reflow around the moved widget to prevent overlaps.

Your layout saves automatically — no save button needed.

## Resizing widgets

Drag the bottom-right corner of any widget to make it larger or smaller. Charts automatically redraw to fit the new dimensions, and tables adjust their visible rows.

This is particularly useful for making important charts wider or giving dense tables more room to breathe.

## Renaming widgets

Click the widget title to edit it inline. Press **Enter** to save or **Escape** to cancel.

By default, the widget title matches your original prompt, but you may want to shorten it or give it a clearer name — for example, renaming "Bar chart of daily sessions for the last 30 days" to simply "Daily Sessions."

## Editing a widget

Click the three-dot menu in the widget header and select **Edit**. This opens the prompt dialog pre-filled with your original description.

Modify the prompt to change what the widget shows — adjust the metric, time range, chart type, or data source — and regenerate. The widget updates in place without changing its position on the grid.

## Deleting a widget

Click the three-dot menu and select **Delete**. The widget is removed immediately and surrounding widgets reflow to fill the gap.

## Reordering dashboards

In the dashboard list, drag dashboards by the grip handle to reorder them. The order persists across sessions, so you can keep your most-used dashboards at the top.
`,
  },

  /* ================================================================ */
  /*  5. Date Ranges & Refresh                                         */
  /* ================================================================ */
  {
    slug: "date-ranges-refresh",
    title: "Date Ranges & Refresh",
    description:
      "Control the time period for your dashboard and keep data fresh.",
    section: "docs",
    category: "dashboards",
    type: "article",
    readTime: "2 min read",
    featured: false,
    keywords: ["date range", "refresh", "cache", "time period", "calendar"],
    content: `---
---

Every dashboard has a date range that controls the time period for all of its widgets. Change it once and every widget updates simultaneously.

<DocsDemo type="date-range" />

## Preset ranges

Click the date button in the dashboard header to see preset options:

- **Last 7 days** — a quick snapshot of the past week
- **Last 28 days** — the default, roughly one month of data
- **Last 90 days** — a quarterly view for spotting longer trends

Select a preset and all widgets re-query with the new time period. The selected range is displayed in the header so you always know what you are looking at.

## Custom ranges

Select **Custom** from the dropdown, or click directly on dates in the calendar. Pick a start date and an end date to define any arbitrary period.

Custom ranges are useful for analysing specific campaigns, promotional periods, or aligning with your reporting calendar.

## How refresh works

Dashboards use a layered caching strategy to balance speed and freshness:

- **Cached data** — When you open a dashboard, widgets show their last-fetched data instantly. There is no loading spinner on first paint.
- **Background refresh** — Immediately after displaying cached data, fresh data is fetched silently in the background. When the new data arrives, widgets update seamlessly.
- **Manual refresh** — Click the refresh icon in the dashboard header to force-update all widgets immediately. Use this when you know new data has landed and you want to see it right away.
- **Date range change** — Changing the date range triggers a full re-query for every widget with the new time period. Cached data for the new range is shown if available, then refreshed.

## Tips

- Dashboards remember their selected date range between sessions. If you set a dashboard to "Last 7 days," it will still show "Last 7 days" the next time you open it.
- Each widget stores its own cached data and a last-refreshed timestamp, so widgets that query different data sources refresh independently.
- If a widget shows stale data from a previous session, the background refresh will update it within a few seconds of opening the dashboard.
`,
  },
];

/* ------------------------------------------------------------------ */
/*  Seed                                                               */
/* ------------------------------------------------------------------ */

async function main() {
  for (const article of articles) {
    await prisma.article.upsert({
      where: { slug: article.slug },
      update: {
        title: article.title,
        description: article.description,
        section: article.section,
        category: article.category,
        type: article.type,
        readTime: article.readTime,
        featured: article.featured,
        keywords: article.keywords,
        content: article.content,
      },
      create: {
        slug: article.slug,
        title: article.title,
        description: article.description,
        section: article.section,
        category: article.category,
        type: article.type,
        readTime: article.readTime,
        featured: article.featured,
        keywords: article.keywords,
        content: article.content,
      },
    });
    console.log(`Seeded: ${article.slug}`);
  }
}

main()
  .then(() => {
    console.log("\nAll dashboard docs seeded successfully.");
    return prisma.$disconnect();
  })
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  });
